php-censor/php-censor

src/B8Framework/Form/Element.php
According to [RFC](https://tools.ietf.org/html/rfc3986#section-3.4). This is not full fix, but it allows you to use percent encoded symbols for e.g. arrays in get queries(it's critical and common usage). If it is important, It can be changed and added by another allowed symbols from RFC.
=> [Form Element] Add percent to setName regex

src/PHPCensor/Builder.php, src/PHPCensor/BuilderException.php, src/PHPCensor/Command/RunCommand.php, src/PHPCensor/Model/Build.php, src/PHPCensor/Store/BuildStore.php, src/PHPCensor/Worker/BuildWorker.php
This fix is mainly for run builds with crontab. But probably this can be useful for run builds with workers.
Ideally, need rewrite the build execution code with lock, check process id, etc.
This fix use sql update status with condition to prevent concurrent processes acquire same build (I saw up to 5 parallel executions one build - if build execution time bigger than crontab schedule period). Also an attempt to correct the wrong work with the loggers in case of failures (the release of the build log was not performed). And the wrong check for the running build of a project.
It is necessary to test the build with workers.
=> Fix build execute - in some cases one build executed with many process

docs/en/plugins/technical_dept.md, src/PHPCensor/Plugin/TechnicalDebt.php
Return Technical Debt Plugin parameters initialisation.
Return Technical Debt Plugin missing parameters description to docs.
Actually just an exact copy-paste from PHPCI.
=> Fix Technical Debt Plugin configuration parameters

docs/en/plugins/php_cpd.md
The 'standard' option is unused in the PhpCpd plugin, and does not actually make sense for copy-paste-detection.
=> Remove copy-paste from phpcpd plugin docs :)

docs/en/workers/worker.md
Link to `cron.md` was invalid in `workers/worker.md` file
=> fix broken link in worker.md file

src/PHPCensor/View/Home/ajax-timeline.phtml, src/PHPCensor/View/Home/index.phtml
Branches in Dashboard->Timeline were always the ones in project settings (Default branch name).
This PR makes sure build branch is displayed, just like it is in build details view.
Thanks.
=> display build branch instead of project branch in Home/index and ajax-timeline

src/PHPCensor/Model/Build/GithubBuild.php, src/PHPCensor/Model/Build/MercurialBuild.php, src/PHPCensor/Model/Build/RemoteGitBuild.php
There are two fixes for GitHub-hosted repositories:
1. There was a typo due to which the status API was broken ob GitHub (https://github.com/corpsee/php-censor/commit/31f92327c12e0cfdb1754650455a9aabc3973924#diff-7e0d0931800d0b6846f60da0d2b19cd6)
2. When working with PR on GitHub the repository is downloaded in a special way:
- At first, the main project's repository is downloaded
- Then a new branch is created with the changes from PR, which are located in the forked repository.
If both of these projects (original and fork) are private, then they should be downloaded using a ssh-key. The issue was that when downloading the fork, this ssh-key was not used.
Therefore it worked with public repositories, but did not work with private ones.
=> Fixed GitHub status API and access to the pull requests of private projects

src/PHPCensor/Model/Build/GithubBuild.php
With this change I added support of `refs/pull` on Github (https://help.github.com/articles/checking-out-pull-requests-locally/).
After this change this scheme will work:
- Organization "Company" has a private repository "Project"
- Mike has read-only access to this repository
- John has access to merge pull requests
- To make some changes in this project Mike creates a Fork of this repository. Then he commit his changes and creates a new Pull Request
- John could view this Pull Request on the original Project's repository (via the Web), but he cannot view the Fork of Mike, because this project is private
- But Github gives us ability to fetch changes from this PR as an external reference on the main repository (`refs/pull/1/head`)
=> Fixed ability to fetch private pull requests on Github

src/PHPCensor/Command/CreateBuildCommand.php
Now builds with full info can be generated from command line.
=> command php-censor:create-build accepts --email and --message

src/PHPCensor/Logging/BuildDBLogHandler.php
It was shown as "/", which is irritating because it looks like root directory.
=> build directory is shown as ./ in log output

docs/en/configuring.md, src/PHPCensor/Command/InstallCommand.php, src/PHPCensor/Controller/WebhookController.php, src/PHPCensor/Helper/Bitbucket.php, src/PHPCensor/Model/Build/BitbucketBuild.php
Added the same functionality as was on the GitHub: build statuses, comments on commits and pull requests, handling webhooks of "pullrequest" event.
=> Bitbucket build status API, create comments on commits and Pull Requests

src/PHPCensor/Model/Build/RemoteGitBuild.php
When building an environment, the attempt to check out the specified commit is erroneous, since the environment is a collection of certain branches.
=> Fix env build - omit checkout exact commit

src/PHPCensor/Command/ScheduleBuildCommand.php, src/PHPCensor/Console/Application.php
For example:
`bash
php bin/console php-censor:schedule-build 1
`
Will check if there are upcoming builds and if there are not, or they are currently not running or pending will schedule a build.
This applies to every project
=> Added command to schedule tasks if not ran for a specified X days

src/PHPCensor/Migrations/20171014173348_removed_project_id_from_build_meta.php
Resolve Issue #127 
- Repair migrations at file `RemovedProjectIdFromBuildMeta`
- Remove foreign key before remove `project_id` field
- Add foreign key at down migration
=> Fix Migrations | Installation Failed

src/PHPCensor/Plugin/PhpParallelLint.php
This is actually a bool already, so it should just read it straight in.
Otherwise:
```
php_parallel_lint:
shorttags: true
```
Won't get applied.
Bugfix
The original version of this expected the option to be a string. This makes it more in keeping with the rest of the option parsing.
=> PhpParallelLint Short tags Option expecting string

src/PHPCensor/Plugin/PhpDocblockChecker.php
This PR logs the error from the PHPDocBlockChecker rather than just logging that the doc block is missing.
Feature
Previously when the docblock checker failed, it would just log that the docblock was missing rather than the actual message coming back from the plugin.
=> PHPDocBlockChecker Plugin Detailed Error Logging

src/Command/CheckLocalizationCommand.php, src/Console/Application.php
new feature on resources
A command to check localization files, with English version :
```
bin/console php-censor:check-localizations
```
You can choose languages list (separated by commas) with "lang" option :
```
bin/console php-censor:check-localizations --langs=fr,ru
```
If you need tags with same translations than English version, vous can choose the "same" option :
```
bin/console php-censor:check-localizations --same=1
```
And you can combine options :
```
bin/console php-censor:check-localizations --langs=fr,ru --same=1
```
=> feature: check localization command

docs/en/plugins/hipchat_notify.md
I was getting the following error:
Class 'HipChat\HipChat' not found
After checking composer.json I saw the `suggest` packages. 
Good to have in the documentation.
Documentation for Hipchat Plugin
Directions on how to install HipChat with composer
=> Installing HipChat via composer

composer.json, composer.lock
I thought I had the standard path wrong but after updating `php_codesniffer` from composer it started reading `phpcs.xml`.
Reference:
https://github.com/squizlabs/PHP_CodeSniffer/issues/1660
Bug: `phpcs.xml` was not read by the plugin, it was defaulting to psr2 causing the built to fail
Updated `composer.json` to install the latest php_codesniffer
=> php_code_sniffer not including phpcs.xml standard

src/Model/Build/LocalBuild.php
Bug fix
When I add a "Local path" project, on a Debian server, I have a problem because the system can copy my files in unknown directory.
=> fix: make directory for local build

docs/en/plugins/php_cs_fixer.md, src/Plugin/PhpCsFixer.php
Bugfix
- Explain the default value of new options in PHP CS Fixer plugin
- added previously dynamically declared `$allowedWarnings` property
- rename option `report-errors` to `report_errors`
=> Explain the default value of new options in PHP CS Fixer plugin

src/Plugin/TechnicalDebt.php
`TechnicalDebt` plugin has used the directory setting as absolute path not as relative like other plugins
Bug fix
Append the directory from config to the build path like in `PhpLoc`
=> Fix directory config option in TechnicalDebt

src/Controller/UserController.php, src/View/User/index.phtml
Bug Fix
On the user listing page, the ```$user``` variable is getting clobbered by the foreach loop resulting in admins only being allowed to edit/delete other admins.
~~Also, the user listing page probably shouldn't be visible by non-admins. Users can still edit their own profile using the link in the top right drop down.~~
Although users can see the /user listing, they can only edit themselves.
=> User Listing Edit Bug

docs/en/configuring_project.md
=> en translation

src/Helper/CommandExecutor.php
The idea of this pull request is not to merge, but to provide some insight into solving issue #217.
I started by analyzing `fgets` behavior ---which may return `false` on error, but that value is not being checked by the code on master.
Since for Codeception's case I noticed that the `while` condition is still true after Codeception finishes, I tried checking the return value of the `stream_select` function.
* With a `null` timeout, or `$timeout = 1;`, the `stream_select` is still blocking indefinitely
* Using a `$timeout = 60;`, I noticed  that `stream_select` returns `1` when Codeception announces it's powered by PHPUnit, returns `0` right before the first test, and then it keeps returning `1` up until Codeception finishes
* In order to use `stream_select`'s return value as part of the …
=> Workaround for issue #217

src/Plugin/Codeception.php
* Bug fix
The `--xml` flag can, optionally, get the name of the report to be generated.
When the args passed to PHP Censor for the Codeception plugin start with a non-flag (e.g., if the value of `test.codeception.args` is `"acceptance --coverage-html --html"`, then the codeception will end up running all the suites (instead of running only the desired one), and generating an XML report named `tests/_output/acceptance`.
Since PHP Censor looks explicitly for `tests/{_output,_log}/report.xml`, the test step will always fail.
Therefore, it's safer to insert the `--xml` flag at the end.
=> Moved the --xml flag to the end of the command

src/Plugin/Codeception.php
Bug fix.
Fixes #247.
I initially thought Codeception was inheriting the `SHELL_VERBOSITY` environment variable, but upon inspecting commit 5f914d5, I noticed `-vvv` was added explicitly. So issue #247 is not really related to issue #212.
For Codeception, the `-vvv` option implies `--steps`, which means that the email sent when the build fails at the testing phase will be huge (in my case, a suite of 80 tests, with ~40 steps per test, results in an email of more than 3200 lines).
The user can always pass `-vvv` as an argument for Codeception using the project's configuration ---but there's no option to remove unwanted verbosity.
=> Remove verbose flag from Codeception's command line

src/Helper/CommandExecutor.php, src/Plugin/Codeception.php
*Bug fix*
Although pull request #229 solves the issue of builds never finishing  when using Codeception (issue #217), it does so in a sub-optimal way.
In general, the issue is that when Codeception finishes, *stdout* remains open, so PHP Censor assumes the process is still running.
Taking into account that PHP Censor already lists Symfony's Process component as a dependency, I reimplemented the `executeCommand` method to use said component for collecting the output of the process being executed, while checking periodically if the process is still running.
Symfony's Process default timeout is 60 seconds, so I changed it to a 86400, just to be sure it won't be an issue.  There's also an *idle* timeout, which I set to 600 seconds.
Codeception doesn't seem to use *stderr*, so in order to …
=> Reimplement executeCommand

composer.json, composer.lock
*Bug fix: PHP Censor should support PHP 7.3, but has outdated Codesniffer dependency that causes PHP warnings. See #334 
Fixed by `composer require "squizlabs/php_codesniffer":"~3.5.0"`
=> PHP Codesniffer updated to 3.5.2 to support PHP 7.3

src/Plugin/TechnicalDebt.php
Replace curly braces with square brackets for PHP 7.4 compatibility
=> PHP 7.4 compatibility fix

src/Store/BuildStore.php
Clicking on _Delete old builds_ fails with `Message: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'OFFSET 100' at line 1`.
MySQL requires LIMIT to use OFFSET.
Use large number as limit to select all builds.
=> Fix deleting of old builds on MySQL

docs/en/configuring_project.md
doc enhancement
Add additional hint that clone_depth is only supported in web-interface.
=> early hint in doc that clone_depth is only supported in web-interface 

src/Plugin/PhpUnit.php
improvement
phpunit checks output file generated by coverage instead of directory.
It reports clearly when the report was not created successfully.
=> phpunit detects more clearly if coverage output was successfully

docs/en/plugins/security_checker.md, src/Plugin/SecurityChecker.php, src/Plugin/Util/SymfonySecurityChecker.php
improvement
Security checker can be configured to use the binary `symfony` (as recommended by https://github.com/FriendsOfPHP/security-advisories#checking-for-vulnerabilities).
=> Symfony security checker

src/Plugin/Sqlite.php
Bugfix.
Fixed #377 (SQLite PDO class constructor evoke with wrong params order).
=> Fixed SQLite plugin PDO initialization. Issue #377.

src/Plugin/Util/Factory.php
*Deprecation fix*
PHP 8 throws the follwing errors:
```
Exception: Deprecated: Method ReflectionParameter::getClass() is deprecated in <PHP_CENSOR_PATH>/src/Plugin/Util/Factory.php line 183
or
Exception: Deprecated: Method ReflectionParameter::isArray() is deprecated in <PHP_CENSOR_PATH>/src/Plugin/Util/Factory.php line 188
```
<br>
Credits: https://php.watch/versions/8.0/deprecated-reflectionparameter-methods
=> Fix PHP 8.0 deprecations

docs/en/plugins/php_stan.md, src/Plugin/PhpStan.php
Bug fix
PHPStan should analyze only subdirectories instead of the main `<BUILD_PATH>`.
Fixes https://github.com/php-censor/php-censor/issues/408
=> Fix: Incorrect directories provided for PHPStan analyse

README.md
Feature
Added 4 lines of text to manual on how to check if Beanstalkd is running, and how to start it.
See also https://github.com/php-censor/php-censor/issues/410
=> Added text on how to check if Beanstalkd is running, and how to start it

src/Plugin/PhpLoc.php, src/Plugin/PhpUnit.php
Bug fix
PHPUnit code coverage was not being generated due to changes in xdebug v3, this will turn on coverage mode if the settings require it.
=> Fix xdebug settings

src/Helper/CommandExecutor.php
Bug fix
> Exception: Deprecated: is_dir(): Passing null to parameter #1 ($filename) of type string is deprecated in <PHP_CENSOR_PATH>/src/Helper/CommandExecutor.php line 238
This is because `CommandExecutor::getComposerBinDir` may return null.
=> PHP 8.1 deprecation while searching for composer binary

docs/en/plugins/telegram_notify.md, src/Plugin/TelegramNotify.php, tests/src/Plugin/TelegramNotifyTest.php
*Improvment TelegramNotify plugin*
These improvements allow to send notifications to individual topics within the telegram group.  The topic ID is separated by a slash after the group ID `-<group id>/<topic id>` in config. You can find out the topic ID using this guide.  https://gist.github.com/nafiesl/4ad622f344cd1dc3bb1ecbe468ff9f8a#get-chat-id-for-a-topic-in-a-group-chat
=> Telegram notify to group topic
