php-censor/php-censor

src/PHPCensor/Model/Build/GogsBuild.php

Added link in error tab for gogs build

add getFileLinkTemplate for gogs

---

src/PHPCensor/Model/Build.php
src/PHPCensor/View/Home/ajax-timeline.phtml
src/PHPCensor/View/Home/index.phtml
src/PHPCensor/View/layout.phtml

if a build is not pending then its duration will be displayed next to last updated time, with time units: 1h 28m 52s

show build duration on Dashboard -> Latest Builds

---

src/PHPCensor/Builder.php
src/PHPCensor/Plugin/Util/Executor.php

Added separate stage for deploy

Add deploy stage

---

docs/en/README.md
docs/en/plugins/mage.md
src/PHPCensor/Plugin/Mage.php

Add deployment with mage (https://github.com/andres-montanez/Magallanes)

Plugin mage

---

src/PHPCensor/Controller/ProjectController.php
src/PHPCensor/Languages/lang.fr.php

- some translations were missing or needed a bit of love.
- fix: project add/edit page was not calling Lang::get() for project group

update french translation

---

src/PHPCensor/Logging/BuildDBLogHandler.php

Current logging very slow оn thousands of lines.

Add write cache to build log (improve speed)

---

src/PHPCensor/Model/Project.php

Added missed handling of default branch name.

Fix get environments by branch - add default branch

---

src/PHPCensor/Command/RunCommand.php
src/PHPCensor/Logging/BuildDBLogHandler.php
src/PHPCensor/Worker/BuildWorker.php

Build log write cache

---

src/PHPCensor/Builder.php
src/PHPCensor/Model/Build.php
src/PHPCensor/Model/Build/GithubBuild.php
src/PHPCensor/Store/BuildErrorWriter.php

Add build error writer (use bulk insert for improve performance)

---

src/PHPCensor/Model/Build/BitbucketBuild.php
src/PHPCensor/Model/Build/BitbucketHgBuild.php
src/PHPCensor/Model/Build/GithubBuild.php

FileLink is generated with commit id for github and bitbucket

---

src/PHPCensor/View/BuildStatus/view.phtml
src/PHPCensor/View/layout.phtml

Fix - invalidate browser cache

---

src/PHPCensor/Controller/WidgetBuildErrorsController.php
src/PHPCensor/Languages/lang.en.php
src/PHPCensor/View/WidgetBuildErrors/empty.phtml

Bug fix
Fix empty build errors - add template and message.

Fix empty build errors - add template and message.

---

src/PHPCensor/Helper/Lang.php

Bug fix
Change condition with back compability

Fixing issue #136 (PHP 7.2 unpack user from session)

---

src/PHPCensor/Plugin/TechnicalDebt.php

* Bug fix
* Feature
* Correctly ignore only relative dir from the start of the path (if you ignored "runtime" all file where ignored)
* add visual representation of checked file 

Feature technical debt fix

---

docs/en/environments.md
src/PHPCensor/Controller/WebhookController.php

* feature
Allows change environments branches with labels in gogs pull requests

Add gogs pull request webhook for manage environments branches

---

README.md

Documentation improvements.
Clean-up and use of original names.

Added small improvements in README.md

---

src/PHPCensor/Plugin/Util/PhpUnitResultJson.php

Php unit json improve

---

docs/en/sources/bitbucket.md

Fix wrong webhook location in description

---

src/Plugin/SensiolabsInsight.php

*bug fix*
*add branch support*

fix sensiolabs insight implementation (branch support)

---

docs/en/plugins/php_docblock_checker.md
src/Plugin/PhpDocblockChecker.php

[PhpDocblockChecker Plugin] add --skip-signatures option

---

.gitignore

* Enhancement.
* Since `public/.htaccess.dist` is commited, `public/.htaccess` should be ignored.

Added .htaccess to .gitignore

---

composer.json
composer.lock
src/Command/InstallCommand.php
src/Migrations/20140513143726_initial_migration.php
src/Migrations/20140513153133_change_build_keys_migration.php
src/Migrations/20140730143702_fix_database_columns.php
src/Migrations/20150203105015_fix_column_types.php
src/Migrations/20151008140800_add_project_groups.php
src/Migrations/20151009100610_remove_unique_name_index.php
src/Migrations/20151014091859_errors_table.php
src/Migrations/20151015124825_convert_errors.php
src/Migrations/20160425162114_branch_column_length.php
src/Migrations/20160623100223_project_table_defaults.php
src/Migrations/20170321131931_add_environment.php
src/Migrations/20170413131256_added_source_column_to_build_table.php
src/Migrations/20171014173348_removed_project_id_from_build_meta.php

I try to fix installation from scratch
Bug fix and a little new feature
- updated phinx via composer update : current version have a Exception() before query, so migration stop without error
- changed the way migration are executed to catch return code and stop installation if migration did not finish
- new phinx version require many $table->save() if not a pending task  error appear

Fix migrations

---

docs/en/plugins/deployer_org.md
docs/en/plugins/git.md
docs/en/plugins/hipchat_notify.md
docs/en/plugins/mage.md
docs/en/plugins/mage3.md
docs/en/plugins/pdepend.md
docs/en/plugins/phing.md
docs/en/plugins/php_cs_fixer.md
docs/en/plugins/php_mess_detector.md

Fix incorrect examples of Mage plugin.
Replace tabs with spaces in yaml examples

Fix Mage plugin documentation

---

src/Plugin/BitbucketNotify.php

Bug fix, feature
- fixed condition to show pdepend in notification
- added PhpUnit-coverage (lines) to message
- added link to message for PhpUnit-Html-CoverageReport

BitbucketNotify - fixed pdepend settings & added phpunit coverage

---

README.md

fix readme and .gitignore

---

docs/en/configuring_project.md

fixed some failures

---

docs/en/configuring_project.md

plugin restrictions

---

docs/en/configuring_project.md

buid stages setup and test

---

docs/en/configuring_project.md

local, global, system, binary_path

---

docs/en/configuring_project.md

deploy, complete, success, failire, fixed, broken

---

composer.json
docs/en/plugins/php_unit.md
src/Plugin/PhpUnit.php
tests/src/Plugin/PhpUnitTest.php

*Feature - resolves #299 *
- added PHPUnit plugin options coverage
- NOT ADDED comparison coverage with previous build

Added PHPUnit plugin options coverage

---

docs/en/plugins/composer.md

doc improvement
indicate in doc that some composer actions may be helpful in test stage

indicate in doc that some composer actions may be helpful in test stage

---

src/Plugin/PhpCsFixer.php
src/Plugin/PhpDocblockChecker.php

improvement
Two plugins do no more show json output in the log.

Improve plugins output

---

composer.json

see https://github.com/maknz/slack/issues/94
up to date dependency
just use supported package for slack

use supported package for slack

---

docs/en/README.md
docs/en/plugins/webhook_notify.md
src/Plugin/Campfire.php
src/Plugin/HipchatNotify.php
src/Plugin/WebhookNotify.php

New plugin
Adds a webhook notify that sends a JSON webhook to a specified URL. Includes plugin, plus usage documentation.

Add WebhookNotify plugin

---

bootstrap.php
src/Languages/lang.id.php

Mostly my country have use this app for their code. Just in case that they want to add this feature so that might be helped them to more understand what they're click

Adding Bahasa Indonesia

---

docs/en/interpolation.md
src/Builder.php
src/Helper/BuildInterpolator.php
src/Plugin/WebhookNotify.php
tests/src/Helper/BuildInterpolatorTest.php
tests/src/PluginTest.php

Feature.
Fixed #374. Added variable for interpolation APP_VERSION (%APP_VERSION%).

Added variable for interpolation APP_VERSION (%APP_VERSION%).

---

docs/en/interpolation.md
src/Builder.php
src/Console/Application.php
src/Helper/BuildInterpolator.php
src/Plugin/Campfire.php
src/Plugin/HipchatNotify.php
src/Plugin/WebhookNotify.php
src/WebController.php

Enhancement.
Improved PHP Censor version variable: renamed APP_VERSION (%APP_VERSION%) to SYSTEM_VERSION (%SYSTEM_VERSION%). #374.

Improved PHP Censor version variable

---

docs/en/plugins/php_cs_fixer.md
src/Plugin/PhpCsFixer.php

Bug fix
This adds support of PHP CS Fixer 3.0.

Fix support of PHP CS Fixer 3.0

---

src/Plugin/Mysql.php
src/Plugin/Pgsql.php
src/Plugin/Sqlite.php

Bug fix
Added interpolate on queries as it allows creating dynamic databases at runtime for testing.
Resubmitted on release-1.3 branch as requested in #415. New PR because I messed up the old branch.

Interpolate sql queries

---

src/Logging/BuildDBLogHandler.php

typo
Looks like a typo if compare to the previous logic.
https://github.com/php-censor/php-censor/blob/a714c21ded16ddad6a8b69509eb1124e1e9c1a38/src/Logging/BuildDBLogHandler.php#L75

Typo in sanitization
